### ISSUE TITLE
Redirects to HTTP instead of HTTPS when using ngrok

### ISSUE THREAD

**Issue by mjallday** [verygoodsecurity/python_demo#25]
Recorded via secure debugger, see screenshot. When I create a card on the merchant portal it redirects from https -> http.

![image](https://user-images.githubusercontent.com/252280/46839830-c8966500-cd74-11e8-8da4-7465d8951340.png)

Running ngrok via `ngrok http  -bind-tls=true -subdomain=vgssl6 192.168.99.100:8080`

Will run without ssl in the meantime but this is annoying.

**Comment by mjallday** [comment]
will be fixed by #26

**Comment by mahmoudimus** [comment]
Fixed by https://github.com/verygoodsecurity/python_demo/pull/26
